[project]
name = "hazbin-tracker"
version = "1.0.9"
description = "Hazbin hotel cards release tracker"
authors = [
    {name = "Dmitrii Shevchenko",email = "47799401+sowwic@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
packages = [
    {include = "hazbin_tracker", from="src"},
]
dependencies = [
    "pyside6 ",
    "requests",
    "platformdirs",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "pytest-qt",
    "ruff",
    "pyinstaller",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-autorefs",
    "mkdocs-autoapi",
]

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"

[tool.ruff]
src = ["src"]
exclude = ["**/resources_rc.py"]

show-fixes = true
line-length = 89
lint.select = [
    "E",
    "F",
    "UP",
    "D",
]
lint.ignore = [
    "D413",
    "D100",
    "D104",
    "D103",
]

[tool.pytest.ini_options]
addopts = "--cov=hazbin_tracker --cov-report=term-missing"
log_cli = true
log_cli_level = "INFO"
